### ISSUE TITLE
Error when building default app

### ISSUE THREAD

**Issue by vaonet-jks** [yoavain/create-windowless-app#1222]
Not sure what I am doing wrong. Any help would be appreciated.

OS Version Windows 2012 R2 (64 bit)
Node Version 12.18.2
MSBuild Version 14.0.25420.1

Creating the app:
```
C:\imprs-sw-portal-9.2\9.2>npx create-windowless-app ws-relay-app --no-typescript --icon C:\imprs-sw-portal-9.2\9.2\WEBMI\basic\images\favicon.ico

Creating a new windowless app in C:\imprs-sw-portal-9.2\9.2\ws-relay-app.

Installing dependencies.

+ node-notifier@10.0.1
+ winston@3.6.0
added 40 packages from 25 contributors and audited 40 packages in 5.248s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Installing dev dependencies.

+ cross-spawn@7.0.3
+ webpack-cli@4.9.2
+ fs-extra@10.0.0
+ webpack@5.69.1
+ rimraf@3.0.2
+ copy-webpack-plugin@10.2.4
+ husky@7.0.4
+ jest@27.5.1
+ nexe@4.0.0-beta.19
added 615 packages from 382 contributors and audited 656 packages in 44.893s

57 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
Using latest nexe release: windows-x64-14.15.3
Building project files.

Building project launcher.

Building launcher with icon: C:\imprs-sw-portal-9.2\9.2\WEBMI\basic\images\favicon.ico.
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/17/2022 9:43:56 AM.
Project "C:\imprs-sw-portal-9.2\9.2\ws-relay-app\launcher\launcher.csproj" on node 1 (default targets).
Compile:
  C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /out:../resources/bin/ws-relay-app-launcher.exe /target:winexe /win32icon:./launc
  her.ico ./launcher.cs
  The output file is ../resources/bin/ws-relay-app-launcher.exe
Done Building Project "C:\imprs-sw-portal-9.2\9.2\ws-relay-app\launcher\launcher.csproj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.93
Done
```

Building the app:
```
C:\imprs-sw-portal-9.2\9.2\ws-relay-app>npm run build

> ws-relay-app@0.1.0 build C:\imprs-sw-portal-9.2\9.2\ws-relay-app
> npm run webpack && npm run nexe


> ws-relay-app@0.1.0 prewebpack C:\imprs-sw-portal-9.2\9.2\ws-relay-app
> rimraf build && rimraf dist


> ws-relay-app@0.1.0 webpack C:\imprs-sw-portal-9.2\9.2\ws-relay-app
> webpack

(node:7540) ExperimentalWarning: The ESM module loader is experimental.
[webpack-cli] HookWebpackError: Only file and data URLs are supported by the default ESM loader
    at makeWebpackError (C:\imprs-sw-portal-9.2\9.2\ws-relay-app\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\imprs-sw-portal-9.2\9.2\ws-relay-app\node_modules\webpack\lib\Compilation.js:3058:12
    at eval (eval at create (C:\imprs-sw-portal-9.2\9.2\ws-relay-app\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:48:1)
    at C:\imprs-sw-portal-9.2\9.2\ws-relay-app\node_modules\webpack\lib\Compilation.js:509:26
    at C:\imprs-sw-portal-9.2\9.2\ws-relay-app\node_modules\copy-webpack-plugin\dist\index.js:708:13
-- inner error --
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:727:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:46:40)
    at link (internal/modules/esm/module_job.js:45:36) caused by plugins in Compilation.hooks.processAssets
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:727:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:46:40)
    at link (internal/modules/esm/module_job.js:45:36)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ws-relay-app@0.1.0 webpack: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ws-relay-app@0.1.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator.WIN2012DEV\AppData\Roaming\npm-cache\_logs\2022-02-17T15_17_57_318Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ws-relay-app@0.1.0 build: `npm run webpack && npm run nexe`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ws-relay-app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator.WIN2012DEV\AppData\Roaming\npm-cache\_logs\2022-02-17T15_17_57_355Z-debug.log
```

**Comment by yoavain** [comment]
I will have a look

**Comment by yoavain** [comment]
@vaonet-jks 
I managed to reproduce it here, so I'll try to debug it later

**Comment by yoavain** [comment]
@vaonet-jks 

Since I'm installing packages at runtime, it's hard keeping track of breaking changes of those packages.
The issue you see is related to a breaking change in `copy-webpack-plugin` which now requires NodeJS version >= 12.20
https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v10.0.0

I can think of 3 options:
1. Update your `NodeJS` version to meet the requirement
2. Install an older version of this `copy-webpack-plugin`
3. Remove the plugin from the `webpack` completely, and copy those resources between the `webpack` script and the `nexe` script (inside the `build` script)
